@FoodOutletRESTAPIDatabase_HostAddress = https://localhost:7277
@id = 10
@foodOutletId=10

//Foodoutlet actions

//Create foodoutlet
POST {{FoodOutletRESTAPIDatabase_HostAddress}}/api/foodoutlet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiNCIsImV4cCI6MTczODE3ODgyMywiaXNzIjoiWW91cklzc3VlciIsImF1ZCI6IllvdXJBdWRpZW5jZSJ9.-KfcIdNxxpPX3dOzlGDNf-BKgmRpPVJ97OnVbY2nzW8
{
  "name": "Admin Cafe",
  "location": "Poznan PL"
}

###

//get all outlets
GET {{FoodOutletRESTAPIDatabase_HostAddress}}/api/foodoutlet

###

//get specific outlet
GET {{FoodOutletRESTAPIDatabase_HostAddress}}/api/foodoutlet/{{id}}
###

//update foodoutelet
PUT {{FoodOutletRESTAPIDatabase_HostAddress}}/api/foodoutlet/{{id}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiNCIsImV4cCI6MTczNzk5NzUwMSwiaXNzIjoiWW91cklzc3VlciIsImF1ZCI6IllvdXJBdWRpZW5jZSJ9.ZiFqJOr-kubtHjzAWFFKWUFoRwQCAOOsmz1W8l99M34
{
  "name": "Stary Browar",
  "location": "poznan"
}

###

//Delete foodoutlet
DELETE {{FoodOutletRESTAPIDatabase_HostAddress}}/api/foodoutlet/{{id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiNCIsImV4cCI6MTczNzk5NzUwMSwiaXNzIjoiWW91cklzc3VlciIsImF1ZCI6IllvdXJBdWRpZW5jZSJ9.ZiFqJOr-kubtHjzAWFFKWUFoRwQCAOOsmz1W8l99M34


###

// Login actions

//correct login
POST {{FoodOutletRESTAPIDatabase_HostAddress}}/api/login/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123"
}

###

//Admin login
POST {{FoodOutletRESTAPIDatabase_HostAddress}}/api/login/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###

//register user
POST {{FoodOutletRESTAPIDatabase_HostAddress}}/api/login/register
Content-Type: application/json

{
  "username": "aksell",
  "password": "123456"
}

###

//Reviews actions

//get all reviews on the api
GET {{FoodOutletRESTAPIDatabase_HostAddress}}/reviews

###

//get all reviews for specific outlet
GET {{FoodOutletRESTAPIDatabase_HostAddress}}/foodoutlets/{{foodOutletId}}/reviews

###

//Post reviews for an outlet using jwt token
POST {{FoodOutletRESTAPIDatabase_HostAddress}}/foodoutlets/{{foodOutletId}}/reviews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiNCIsImV4cCI6MTczODE2NzUxMCwiaXNzIjoiWW91cklzc3VlciIsImF1ZCI6IllvdXJBdWRpZW5jZSJ9.pmsnTfSlRQF-q3kpuEJ_y2dTfUeE_xmcUEAzM2B3OCg
{
  "comment": "admin reviews 3",
  "score": 2
}

###

###

//Extra actions

//get average ratings for specific outlet
GET {{FoodOutletRESTAPIDatabase_HostAddress}}/foodoutlets/{{id}}/average-rating

###

//top rated outlets
GET {{FoodOutletRESTAPIDatabase_HostAddress}}/foodoutlets/top-rated

###
GET {{FoodOutletRESTAPIDatabase_HostAddress}}/api/login/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdHVzZXIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIxIiwiZXhwIjoxNzM4MTg1MzM3LCJpc3MiOiJZb3VySXNzdWVyIiwiYXVkIjoiWW91ckF1ZGllbmNlIn0.47xXj7TFmdEK-FENoTiCWhje0lvjzuJVv-SO9pzeOVg
###
